version: "2"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  # make sure that you specify correct volume to be mounted
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data

  hive-metastore:
    build: ./hive
    image: hive-metastore:latest
    ports:
    - 9083:9083
    depends_on:
      - mariadb
  
  trino:
    image: trinodb/trino:latest
    ports:
      - 8080:8080
    volumes:
      - ./trino/etc:/usr/lib/trino/etc:ro
      - ./trino/catalog:/etc/trino/catalog

  superset:
    image: viet1846/superset-dev:latest
    ports:
      - 8088:8088
    volumes:
      - ./superset/data:/app/superset_home
